import Head from "next/head";
import Navbar from "@/components/Navbar";
import Hero from "@/sections/Hero";
import About from "@/sections/Projects";

export default function Home() {
  return (
    <>
      <Head>
        <title>moon-folio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="scroll-smooth">
        <Hero />
        <About />
      </main>
    </>
  );
}


