import Head from "next/head";
import Navbar from "@/components/Navbar";
import { components } from "@/data/layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>moon-folio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className="scroll-smooth">
        {components.map((component, id)=>
          <div key={id} id={component.id}>
            {component.render}
          </div>
        )}
      </main>
    </>
  );
}


