import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>moon-folio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className="hero">
      <h1>Hi</h1>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque ipsam aspernatur repudiandae ullam a provident ab magni ipsum numquam nihil?</p>
    </div>
    </>
  );
}
